### ISSUE TITLE
ImportError: cannot import name 'AgentPolicy' from 'smarts.core.agent'

### ISSUE THREAD

**Issue by Aflexiblebox** [MCZhi/Expert-Prior-RL#1]
Hello, When I run `scl run --envision expert_recording.py left_turn --samples 40`,there are an error like title.

![图片](https://user-images.githubusercontent.com/30164440/156924007-5be2ddb6-5a6b-4d42-829b-327eaf1706cb.png)

I don't know why it doesn't work.I'm already install all the requirement.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Finaly I find the reason,  After SMARTS 5.0

> Removed deprecated class `AgentPolicy` from `agent.py`.

I think you'd better list the version of SMARTS in `README.md`.

Thank you for your code very much, I have read you paper repeatedly, it's very great and remarkable! And It's very helpful to me~

**Comment by MCZhi** [comment]
Hello. I think the problem is caused by the latest version of SMARTS. You can try downgrading the SMARTS to version 0.4.17.

**Comment by champcui** [comment]
> Hello, When I run `scl run --envision expert_recording.py left_turn --samples 40`,there are an error like title.
> 
> ![图片](https://user-images.githubusercontent.com/30164440/156924007-5be2ddb6-5a6b-4d42-829b-327eaf1706cb.png)
> 
> ## I don't know why it doesn't work.I'm already install all the requirement.
> Finaly I find the reason, After SMARTS 5.0
> 
> > Removed deprecated class `AgentPolicy` from `agent.py`.
> 
> I think you'd better list the version of SMARTS in `README.md`.
> 
> Thank you for your code very much, I have read you paper repeatedly, it's very great and remarkable! And It's very helpful to me~



> 



> >
 Excuse  me, I meet the same questions. But I am sure that  I use SMARTS 0.4. How to solve that problems?

**Comment by MCZhi** [comment]
You can try using import `Agent` instead of `AgentPolicy` and replace `AgentPolicy` with `Agent` in the file.

**Comment by champcui** [comment]
> 

Thanks for your reply! Actually, there was another problems"TypeError: __init__() got an unexpected keyword argument 'policy_builder" after replace AgentPolicy with Agent in the file.

**Comment by MCZhi** [comment]
Please replace `policy_builder` with `agent_builder`.

**Comment by champcui** [comment]
> Please replace `policy_builder` with `agent_builder`.

I meet another problems after use that. Now I think there was a problem wiht smarts 0.4.8 or which kinds smarts did you use? 0.4.X?

**Comment by champcui** [comment]
smarts.core.vehicle.RendererException: A renderer is required to add an RGB camera. You may not have installed the [camera-obs] dependencies required to render the camera sensor observations. Install them first using the command `pip install -e .[camera-obs]` at the source directory.

Excuse me, there was a new question.

**Comment by MCZhi** [comment]
I was using smarts 0.4.17. Based on the information you provide, I guess the problem is that you did not install smarts properly. I suggest reinstalling the simulator and making sure you follow the guidelines and pass the test.

**Comment by champcui** [comment]
Excuse me, I meet that problem as next two photos. Thanks for your reply.

> I was using smarts 0.4.17. Based on the information you provide, I guess the problem is that you did not install smarts properly. I suggest reinstalling the simulator and making sure you follow the guidelines and pass the test.

Excuse me, I meet that problem as next two photos. Thanks for your reply.
![2022-09-24 16-45-40 的屏幕截图](https://user-images.githubusercontent.com/69706359/192089343-a4778250-a47c-41e1-a6da-b3a939720aa6.png)
![2022-09-24 16-45-36 的屏幕截图](https://user-images.githubusercontent.com/69706359/192089345-6845d89c-a777-4371-80de-3a192213bdaf.png)

**Comment by champcui** [comment]
> I was using smarts 0.4.17. Based on the information you provide, I guess the problem is that you did not install smarts properly. I suggest reinstalling the simulator and making sure you follow the guidelines and pass the test.

Excuse me,  there were another questions.
![2022-09-27 02-18-29 的屏幕截图](https://user-images.githubusercontent.com/69706359/192351420-99d45ea8-7acf-40a4-bdfd-6f2129c7e8bd.png)
![2022-09-27 02-18-27 的屏幕截图](https://user-images.githubusercontent.com/69706359/192351432-5d98c1ec-f1b0-4aa6-9fdf-270b14a661ce.png)
