### ISSUE TITLE
Error  no such command "run"

### ISSUE THREAD

**Issue by hu-jerry** [MCZhi/Expert-Prior-RL#3]
Hello, When I run scl run --envision expert_recording.py left_turn --samples 40, there are an error "no such command "run" ".
I don't know why it doesn't work. I have installed all the requirement.

**Comment by MCZhi** [comment]
Hello, I am not sure the reason. But I guess it may be because of the version of SMARTS. Make sure the version is 0.4.x.

**Comment by Jihong-Kim97** [comment]
Hello, I got same issue [I run scl run --envision expert_recording.py left_turn --samples 40, there are an error "no such command "run" ] and I found that SMARTS(v0.4.5)'s scl has just three commands(envision, sceanrio, zoo) as the image under. Thank you
![image](https://github.com/MCZhi/Expert-Prior-RL/assets/76779465/3065394d-2fe2-44a4-a1b5-5a8915e79d4c)
