### ISSUE TITLE
Exception encountered when calling layer "gaussian_policy"

### ISSUE THREAD

**Issue by wangym0928** [MCZhi/Expert-Prior-RL#5]
When I run "python train.py value_penalty left_turn --prior expert_model/left_turn", I meet the follow error.What shold I do to solve this problem?

ValueError: Exception encountered when calling layer "gaussian_policy" (type ExpertGuidedGaussianActor).

Argument diag must have at least 1 dimension.  Found: tf.Tensor(nan, shape=(), dtype=float32)

Call arguments received by layer "gaussian_policy" (type ExpertGuidedGaussianActor):
  • states=tf.Tensor(shape=(1, 80, 80, 9), dtype=float32)
  • test=False

**Comment by MCZhi** [comment]
Sorry for the very late replay. May I know which version of tensorflow and tensorflow-probability you are using?
