### ISSUE TITLE
Error: No such command 'run'.

### ISSUE THREAD

**Issue by Jihong-Kim97** [MCZhi/Expert-Prior-RL#6]
Hello, I got same issue [I run scl run --envision expert_recording.py left_turn --samples 40, there are an error "no such command "run" ]
![image](https://github.com/MCZhi/Expert-Prior-RL/assets/76779465/d59389c8-e7d8-4952-8a75-ae30fe135acb) 
and I found that SMARTS(v0.4.5)'s scl has just three commands(envision, sceanrio, zoo) as the image under. Thank you!
![image](https://github.com/MCZhi/Expert-Prior-RL/assets/76779465/2a0d8b77-4626-449d-a0c6-60f981cde592)

**Comment by MCZhi** [comment]
Hello, thank you for reaching out. I don't know why the `scl run` command isn't functioning properly. However, a possible solution would be to open an `envision` window from `smarts` in your web browser and use `python expert_recording.py` to gather expert demonstrations instead.

**Comment by MCZhi** [comment]
By the way, which version of smarts simulator are you using? Maybe you can try version 0.4.17.

**Comment by Jihong-Kim97** [comment]
Thank you for your responding! I'm using SMARTS 0.4.5 for now, I will try the solutions you give me.
