### ISSUE TITLE
difficult to collect the exeprt data

### ISSUE THREAD

**Issue by Jihong-Kim97** [MCZhi/Expert-Prior-RL#7]
Hello, I run expert_recoding.py(left_turn scenario) to demonstrate how to drive(🠉 speed up, 🠋 slow down, 🠈 turn left, 🠊 turn right) and I found that it's really hard to reach goal without any collisions with default settings. Also, the image below show that speed of agent in UI(3.31) and vehicle speed on the terminal that I print from lane_following_controller.py is different.
![image](https://github.com/MCZhi/Expert-Prior-RL/assets/76779465/c63def82-986b-4592-9cce-1913599662fa)

**Comment by MCZhi** [comment]
The discrepancy between the actual speed and the speed shown in UI does not influence data collection and model training. The program would record the actual speed from the simulator. If you think the left turn scenario might be too difficult, you can try using the roundabout scenario, which should be easier.

**Comment by Jihong-Kim97** [comment]
Is there anyway to get expert data or expert model? or do you have plan to provide those?

**Comment by MCZhi** [comment]
Sorry, we do not have plans to provide expert data or models. You may use the code to collect the data and train the expert model.
