### ISSUE TITLE
TypeError: cannot inherit non-frozen dataclass from a frozen one

### ISSUE THREAD

**Issue by wolf2127** [MCZhi/Expert-Prior-RL#8]
Hello, when I try to run the command line scl run --envision expert_recording.py left_turn --samples 40, it reports the following error, can you tell me what this is probably due to? Thank you very much for your answer!
![2024-04-22 19-41-00 的屏幕截图](https://github.com/MCZhi/Expert-Prior-RL/assets/116620093/17aaee32-c367-473c-987e-c010cf0af1fe)

**Comment by MCZhi** [comment]
From the information, it seems this is a problem due to the SMARTS simulator. I suggest testing if the simulator is installed properly and testing some simple cases on the simulator. If that still doesn't work, you may try downgrading the simulator version to 0.4.16 or 0.4.15.

**Comment by wolf2127** [comment]
Ok, I appreciate being able to hear from you and apologize for only getting back to you. I'll give it a try regarding your suggestion, thanks!

**Comment by PlayerG1** [comment]
> Ok, I appreciate being able to hear from you and apologize for only getting back to you. I'll give it a try regarding your suggestion, thanks!
hi, i meet the same problem,have you resolved this issue yet?

**Comment by PlayerG1** [comment]
hi, i meet the same problem,have you resolved this issue yet?
